### ISSUE TITLE
custom_size_t_hash in youtube video

### ISSUE THREAD

**Issue by petrasvestartas** [ranjeethmahankali/galproject#18]
Hi,

I am following mesh clip youtube video:
https://www.youtube.com/watch?v=t6VvtW8y9q4

What does _custom_size_t_hash_ stands for?
In this repository I cannot find any implementation of this type

**Comment by ranjeethmahankali** [comment]
Hey, sorry I missed this earlier. I renamed it to CustomSizeTHash in Util.h. Hope you found it!
